// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _210626_Syntra_Emese_WebAPI_EF_Oef.DB;

namespace _210626_Syntra_Emese_WebAPI_EF_Oef.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("ProductsproductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoriesID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductsproductID", "categoriesID");

                    b.HasIndex("categoriesID");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("_210626_Syntra_Emese_WebAPI_EF_Oef.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categorieName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("_210626_Syntra_Emese_WebAPI_EF_Oef.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("productName")
                        .HasColumnType("TEXT");

                    b.Property<int>("productPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("productID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("_210626_Syntra_Emese_WebAPI_EF_Oef.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsproductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_210626_Syntra_Emese_WebAPI_EF_Oef.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("categoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
